/**
 * A (Sonatype Nexus Repository Manager) component
 */
export class Component {
    /**
     * Path generated by Nexus out Maven groupID, artifactID and version. Taken from first asset
     */
    public path: string = ''

    /**
     * Id of the component within Sonatype Nexus Repository Manager
     */
    public id: string = ''

    /**
     * Version of the component, taken from Maven version
     */
    public version: string = ''

    /**
     * last modified timestamp, taken by the first asset of the component
     */
    public timestamp: Date = new Date()

    /**
     * Sets the value for date
     *
     * @param value String which is convertable into a date
     * @returns the instance itself
     */
    public withDate(value: string) {
        this.timestamp = new Date(value)
        return this
    }

    /**
     * Sets the value for path
     *
     * @param value Path of the component
     * @returns the instance itself
     */
    public withPath(value: string) {
        this.path = value
        return this
    }

    /**
     * Sets the value for id
     *
     * @param value The id of the component
     * @returns the instance itself
     */
    public withId(value: string) {
        this.id = value
        return this
    }

    /**
     * Sets the value for version
     *
     * @param value The version of the component
     * @returns the instance itself
     */
    public withVersion(value: string) {
        this.version = value
        return this
    }
}
